//
// Created by pucci on 04/06/2024.
//

#ifndef LABORATORIO_PROGRAMMAZIONE_LISTASPESA_H
#define LABORATORIO_PROGRAMMAZIONE_LISTASPESA_H


class ListaSpesa {

};


#endif //LABORATORIO_PROGRAMMAZIONE_LISTASPESA_H
